### ISSUE TITLE
perf missing form type-enum

### ISSUE THREAD

**Issue by marionebl** [marionebl/conventional-changelog-lint-config-angular#2]

**Comment by cogell** [comment]
any word on when this will get released?

**Comment by marionebl** [comment]
Thanks for the heads up: https://github.com/marionebl/conventional-changelog-lint-config-angular/releases/tag/v0.2.3

**Comment by marionebl** [comment]
Released on upstream conventional-changelog-lint: https://github.com/marionebl/conventional-changelog-lint/releases/tag/v1.0.0

**Comment by cogell** [comment]
thanks!
